services:
  - type: web
    name: shipment-tracker
    env: php
    plan: free
    branch: main
    root: .
    buildCommand: composer install --no-dev --optimize-autoloader
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT
    preDeployCommand: |
      php artisan migrate --force
      # php artisan db:seed --force
      php artisan config:clear
      php artisan cache:clear
      php artisan config:cache
      php artisan route:cache
      php artisan view:clear
    envVars:
      - key: APP_NAME
        value: "Shipment Tracker"
      - key: APP_ENV
        value: "production"
      - key: APP_KEY
        value: "base64:K1h+gIh9TtT3Qm6n7vXyz5dAb3Qx1ZkF3j+gO7H6fL4="
      - key: APP_CIPHER
        value: "aes-256-cbc"
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: "https://shipmenttracking-3.onrender.com"
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d756naq4d50c73e66mmg-a
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: shipment_tracker
      - key: DB_USERNAME
        value: shipment_tracker_user
      - key: DB_PASSWORD
        value: "<your-db-password>"
      - key: SESSION_DRIVER
        value: "file"
      - key: CACHE_STORE
        value: "file"
      - key: QUEUE_CONNECTION
        value: "sync"
      - key: FILESYSTEM_DISK
        value: "local"
      - key: MAIL_MAILER
        value: "log"
      - key: MAIL_FROM_ADDRESS
        value: "hello@example.com"
      - key: MAIL_FROM_NAME
        value: "Shipment Tracker"